apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-03-17T01:16:49Z"
  generation: 1
  labels:
    app: jhttp
  name: jhttp
  namespace: default
  resourceVersion: "151721"
  uid: 2d59e4c2-0b1d-4607-bba8-59adfae69665
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jhttp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jhttp
    spec:
      containers:
      - image: dmontanez/jhttp_state:11
        imagePullPolicy: IfNotPresent
        name: jhttp-state-hc2cp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
