{{- if .Values.createNamespace}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
{{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: my-jhttp-svc
  labels:
    app: jhttp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: jhttp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jhttp
  name: jhttp
  namespace: {{.Values.namespace}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jhttp
  template:
    metadata:
      labels:
        app: jhttp
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: IfNotPresent
        name: jhttp-state-hc2cp
        ports:
        - containerPort: 80
