apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jhttp
  name: jhttp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhttp
  template:
    metadata:
      labels:
        app: jhttp
    spec:
      containers:
      - image: dmontanez/jhttp_state:11
        imagePullPolicy: IfNotPresent
        name: jhttp-state-hc2cp
        ports:
        - containerPort: 80
